import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const handleOnChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    // もし末尾に「?」もしくは「？」があれば、ChatGPTのAPIを叩く
    if (e.target.value.match(/[\?|？]$/)) {
      // ChatGPTのAPIを叩く
      console.log("ChatGPTのAPIを叩く");
    }
  };

  return (
    <>
      <Head>
        <title>ChatGpt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <textarea
            className={styles.memoTextarea}
            onChange={(e) => handleOnChange(e)}
          ></textarea>
        </div>
      </main>
    </>
  );
}
