import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import axios from "axios";

export default function Home() {
  const handleOnChange = async (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const chat: string = `以下の文章から、ユーザーの悩みを察知してアドバイスをください。\n\n${e.target.value}`;
    // もし末尾に「?」もしくは「？」があれば、ChatGPTのAPIを叩く
    if (chat.match(/[\?|？]$/)) {
      // ChatGPTのAPIを叩く
      console.log("Waiting for ChatGPT...");
      const res = await axios.get("/api/chatgpt?chat=" + chat);
      const data = await res.data;
      console.log(data.chat);
    }
  };

  return (
    <>
      <Head>
        <title>ChatGpt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <textarea
            className={styles.memoTextarea}
            onChange={(e) => handleOnChange(e)}
          ></textarea>
        </div>
      </main>
    </>
  );
}
